### ISSUE TITLE
Infinite Sea by Aury88

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubports-wallpapers#1]
Author: Aury88
License: [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)
Resolution: 4096x4096px

### Preview

![low-resolution preview - Infinite Sea](https://user-images.githubusercontent.com/21966173/46612876-5ce39c00-cad7-11e8-8214-c92c8351a6e7.png)

### Download

I don't know if GitHub recompresses files, so here's the full-resolution image in a zip:

[Sea.zip](https://github.com/ubports/ubports-wallpapers/files/2456188/Sea.zip)

**Comment by NeoTheThird** [comment]
Man, this is pretty!

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/lomiri-wallpapers/-/issues/1.
