### ISSUE TITLE
probably wrong suggested resolution

### ISSUE THREAD

**Issue by Aury88** [ubports/ubports-wallpapers#2]
Hi all!
The suggested resolution in the "Submission rules" paragraph in README  probably is not the most convenient for the ultraHD.
The 4096 px resolution is used mainly in digital cinema production/movie projection industry.
In television and consumer media, 3840 (4K UHD) is the dominant 4K standard:
This is the resolution of the UHDTV1 format defined in SMPTE ST 2036-1,as well as the 4K UHDTV format defined by ITU-R in Rec. 2020, and is also the minimum resolution for CEA's definition of Ultra HD displays and projectors.The resolution of 3840 × 2160 was also chosen by the DVB Project for their 4K broadcasting standard, UHD-1. (from [Wikipedia](https://en.wikipedia.org/wiki/4K_resolution))

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/lomiri-wallpapers/-/issues/2.
