### ISSUE TITLE
Kleiber Wallpaper

### ISSUE THREAD

**Issue by luksus42** [ubports/ubports-wallpapers#4]
Author: Lukas Baubkus
License: [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/)
Resolution: 6028x3391px

![Kleiber](https://user-images.githubusercontent.com/6659488/96385998-e1258b00-1197-11eb-9b13-43ce1d7ee440.jpg)
![portrait](https://user-images.githubusercontent.com/6659488/96386114-c1429700-1198-11eb-99ef-80722ee95dec.png)
![landscape](https://user-images.githubusercontent.com/6659488/96386115-c3a4f100-1198-11eb-8f75-917a4e9bdfdc.png)

[Kleiber.jpg.zip](https://github.com/ubports/ubports-wallpapers/files/5398191/Kleiber.jpg.zip)

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/lomiri-wallpapers/-/issues/4.
