### ISSUE TITLE
painting colors

### ISSUE THREAD

**Issue by herobrine7gamer** [ubports/ubports-wallpapers#6]
Author : HEROBRINE7GAMER
License : CC-BY-SA 3.0
Resolution : 6000 × 4000 px

![painting_colors](https://user-images.githubusercontent.com/84784030/143734286-3691d160-15d2-4718-841e-f0a8515fcd8d.jpg)

**Comment by Flohack74** [comment]
Very nice! Could you directly open a PR to the codebase, so then we could merge it easily :)

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/lomiri-wallpapers/-/issues/6.
